// NOTE this file is added to public/lib because it is copied to extensions
// automatically. extensions import it in background page
export default {
  TYPE_ERR: 0,
  TYPE_TEXT: 1,
  TYPE_HTML: 2,
  TYPE_XML: 4,
  TYPE_FEED: 5,
  TYPE_FORM: 6,
  TYPE_PDF_HTML: 7,
  TYPE_DOC: 8,
  TYPE_JSON: 9,

  TYPE_RULE: 1,
  TYPE_RULE_GROUP: 2,

  OP_AND: 1,
  OP_OR: 2,

  CONTENT_TYPE_TEXT: 1,
  CONTENT_TYPE_CHANGED_TEXT: 2,
  CONTENT_TYPE_OLD_TEXT: 3,

  RULE_NOT_EMPTY: 1,
  RULE_HAS_TEXT: 2,
  RULE_HAS_TEXT_NOT: 3,
  RULE_HAS_NUMBER_LT: 4,
  RULE_HAS_NUMBER_GT: 5,
  RULE_HAS_NUMBER_DECR_MIN: 6,
  RULE_HAS_NUMBER_INCR_MIN: 7,
  RULE_MATCH_REGEX: 8,
  RULE_HAS_NUMBER_DECR_PERCENT_MIN: 9,
  RULE_HAS_NUMBER_INCR_PERCENT_MIN: 10,

  STATE_DEFAULT: 0,
  STATE_NEW: 10,
  STATE_INIT: 20,
  STATE_UNAUTHORIZED: 30,
  STATE_AUTHORIZED: 35,
  STATE_READY: 40,
  STATE_PAUSED: 45,
  STATE_RESTRICTED: 50,
  STATE_DISCARD: 90,
  STATE_DEL: 100,
  STATE_DONE: 100,
  STATE_PLAN_PUBLIC   : 0,
  STATE_PLAN_PRIVATE  : 70,
  STATE_ARCHIVED: 110,	


  STATE_ATTR_VERIFY: 10,
  STATE_ATTR_VERIFY_INIT: 20,
  STATE_ATTR_VERIFY_WAIT: 30,
  STATE_ATTR_VERIFY_DONE: 40,

  ACTION_EMAIL: 1,
  ACTION_SMS: 2,
  ACTION_PUSH: 3,
  ACTION_MACRO: 4,
  ACTION_WEBHOOK: 5,
  ACTION_SLACK: 6,
  ACTION_DISCORD: 7,


  ACTION_LOCAL_AUDIO: 101,
  ACTION_LOCAL_POPUP: 102,
  ACTION_LOCAL_OPEN_TAB: 103,

  RUN_STATE_INIT: 1,
  RUN_STATE_WAIT: 2,
  RUN_STATE_WIP: 3,

  LOCAL_STATE_SYNCED: 0,
  LOCAL_STATE_POST: 1,
  LOCAL_STATE_PUT: 2,
  LOCAL_STATE_DEL: 3,
  LOCAL_STATE_POST_ERR: 10,
  LOCAL_STATE_PUT_ERR: 20,
  LOCAL_STATE_DEL_ERR: 30,

  CLIENT_FF: 10,
  CLIENT_CR: 11,
  CLIENT_OP: 12,
  CLIENT_FFWX: 13,
  CLIENT_MSE: 14,
  CLIENT_ELECTRON: 15,

  CLIENT_MAC: 20,

  CLIENT_WEBFF: 50,
  CLIENT_DEDI: 51,

  CLIENT_ANY: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
  CLIENT_WEB: 'ffffffff-ffff-ffff-ffff-ffffffffffff',

  CLIENT_ACTIVE: 15,	
  CLIENT_INACTIVE: 25,	
  CLIENT_DISCONN: 45,	
  CLIENT_INVALID: 55,

  SOURCE_SITEMAP: 1,

  DEFAULT_GROUPID: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',

  TIME_INFINITE: 2592000, // Roughly 30 days


  NUM_FORMAT_COMMA_DOT: '1,.',
  NUM_FORMAT_DOT_COMMA: '2.,',
  NUM_FORMAT_SPACE_COMMA: '3 ,',

  DS_TYPE_JSON: 'json',
  DS_TYPE_SCRAPEX_SCRAPER: 'scrapex_scraper',
  DS_TYPE_SCRAPEX_SCRIPT:  'scrapex_script',
  DS_TYPE_UPTIME: 'uptime',

  DS_ID_JSON: '00000000-0000-0000-0000-000000000001',
  DS_ID_UPTIME: '00000000-0000-0000-0000-000000000002',

  PRODUCT_ID_DISTILL: 1,
  PRODUCT_ID_SCRAPEX: 2,

  PRODUCT_DISTILL: "Distill Web Monitor",
  PRODUCT_SCRAPEX: "Scrapex.ai",
};

